### PR TITLE
Fix usage of Helm global values

### PR DESCRIPTION
**Pull request by spremel**
The implicit scoping of subcharts values breaks the usage of global values.
I modified it to make sure "global" sections is never scoped.
 
See the test added in `__fixtures__/with-subcharts` for an example.

The last two commits are unrelated to the issue.

### CODE REVIEW

**Comment by spremel** [comment]
Hello @vbehar,
It's been a few weeks since the P.R. Are you still maintaining the repository ?
Thanks

**Comment by vbehar** [comment]
hi, sorry I totally missed your PR. I'll have a look tomorrow

**Review by vbehar — APPROVED** [review]

**Comment by vbehar** [comment]
thanks for your work. I'll fix the CI

**Comment by vbehar** [comment]
ok you can use v1.0.16 https://github.com/vbehar/helm3-unittest/releases/tag/v1.0.16

**Comment by spremel** [comment]
Perfect.
Thank you !

**Pull request merged**
